services:
  db:
    image: postgres:17
    container_name: local_db
    restart: always
    environment:
      POSTGRES_DB: springboot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: spring_app
    env_file:
      - .env
    depends_on:
      - db
    expose:
      - 8080
    ports:
      - "8080:8080"

volumes:
  postgres_data: