name: Build, Test, and Deploy on PR

on:
  pull_request:
    branches: [ test ]  # Runs on PRs targeting the 'test' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Deploy to VPS and Restart Spring Boot
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            # Navigate to the application directory
            cd /home/user/my-spring-boot-app || exit 1

            # Stop the running application
            pkill -f 'java -jar' || echo "No process found"

            # Pull the latest code
            git checkout master
            git pull origin master

            # Create or update the .env file
            cat <<EOF > .env
            MY_DB_URL=${{ secrets.MY_DB_URL }}
            MY_DB_USERNAME=${{ secrets.MY_DB_USERNAME }}
            MY_DB_PASSWORD=${{ secrets.MY_DB_PASSWORD }}
            MY_GITHUB_OAUTH_CLIENT_ID=${{ secrets.MY_GITHUB_OAUTH_CLIENT_ID }}
            MY_GITHUB_OAUTH_CLIENT_SECRET=${{ secrets.MY_GITHUB_OAUTH_CLIENT_SECRET }}
            MY_SERVER_PORT=${{ secrets.MY_SERVER_PORT }}
            MY_JWT_SECURITY_KEY=${{ secrets.MY_JWT_SECURITY_KEY }}
            MY_JWT_SECURITY_KEY_EXP_TIME=${{ secrets.MY_JWT_SECURITY_KEY_EXP_TIME }}
            MY_REFRESH_TOKEN_TTL=${{ secrets.MY_REFRESH_TOKEN_TTL }}
            MY_CLIENT_URL=${{ secrets.MY_CLIENT_URL }}
            MY_GOOGLE_DRIVE_ID=${{ secrets.MY_GOOGLE_DRIVE_ID }}
            MY_APPLICATION_NAME=${{ secrets.MY_APPLICATION_NAME }}
            EOF

            # Build the application
            mvn clean package -DskipTests

            # Start the application with the .env file
            nohup java -jar target/demo-0.0.1-SNAPSHOT.jar --spring.config.location=/home/user/my-spring-boot-app/.env > app.log 2>&1 &

            # Verify the application is running
            sleep 5
            ps aux | grep demo-0.0.1-SNAPSHOT.jar
